apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: vandiemmy/location:main
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: location
spec:
  type: NodePort
  selector:
    app: location
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31084