apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          image: vandiemmy/rating:main
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  type: NodePort
  selector:
    app: rating
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088