apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: vandiemmy/inventory:main
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31090